# Generated by Django 5.1.5 on 2025-01-31 08:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.JSONField()),
                ('topic', models.CharField(db_index=True, max_length=255)),
                ('difficulty', models.PositiveSmallIntegerField()),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('others', models.TextField(blank=True, null=True)),
                ('image_base64', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['topic', 'difficulty', 'school'], name='quickstart__topic_f2d1e0_idx')],
            },
        ),
    ]
