# Generated by Django 5.1.5 on 2025-01-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionbank',
            old_name='image_base64',
            new_name='options_image_base64',
        ),
        migrations.AddField(
            model_name='questionbank',
            name='question_image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
