# Generated by Django 5.1.5 on 2025-01-31 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_rename_image_base64_questionbank_options_image_base64_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionbank',
            name='difficulty',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='topic',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
