# Generated by Django 5.1.5 on 2025-02-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_alter_questionbank_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='questionbank',
            name='quickstart__topic_f2d1e0_idx',
        ),
        migrations.AddField(
            model_name='questionbank',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='question_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['topic', 'difficulty', 'school', 'active'], name='quickstart__topic_b090af_idx'),
        ),
    ]
