# Generated by Django 5.1.5 on 2025-02-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_remove_questionbank_quickstart__topic_f2d1e0_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('option', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='topic',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
