# Generated by Django 5.1.5 on 2025-02-11 14:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_labeloptions_alter_questionbank_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labeloptions',
            name='id',
        ),
        migrations.AddField(
            model_name='labeloptions',
            name='label_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
