# Generated by Django 5.1.5 on 2025-02-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_remove_labeloptions_id_labeloptions_label_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='discrimation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='guessing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='difficulty',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
